// Wusstest du? – kindgerechte Mini-Fakten (Vorschule / 1. Klasse).
// Über 200 Stück; pickFact() merkt sich im localStorage, welche schon
// gezeigt wurden, damit sich Fakten auch über mehrere Lektionen hinweg
// erst dann wiederholen, wenn alle einmal dran waren.

const F = (emoji, text) => ({ emoji, text });

export const FUN_FACTS = [
  // ---------- Tiere ----------
  F("🐘", "Ein Elefant kann mit seinem Rüssel schnorcheln wie du im Schwimmbad!"),
  F("🐘", "Elefantenbabys lutschen am Rüssel – so wie manche Kinder am Daumen!"),
  F("🐘", "Ein Elefant trinkt an einem Tag so viel Wasser wie eine ganze Badewanne!"),
  F("🦒", "Eine Giraffe hat eine dunkelblaue Zunge – so lang wie dein Arm!"),
  F("🦒", "Giraffen schlafen nur ganz kurz – oft nur ein paar Minuten am Stück!"),
  F("🦒", "Giraffenbabys sind schon bei der Geburt größer als ein Erwachsener!"),
  F("🐙", "Ein Oktopus hat drei Herzen und acht Arme!"),
  F("🐙", "Oktopusse können ihre Farbe ändern und sich so verstecken!"),
  F("🦋", "Schmetterlinge schmecken mit ihren Füßen!"),
  F("🐛", "Jeder Schmetterling war zuerst eine Raupe!"),
  F("🐝", "Bienen tanzen, um ihren Freunden den Weg zu den Blumen zu zeigen!"),
  F("🐝", "Für ein Glas Honig fliegen Bienen so weit wie dreimal um die ganze Erde!"),
  F("🐧", "Pinguine können nicht fliegen, aber super schnell schwimmen!"),
  F("🐧", "Pinguin-Papas halten das Ei wochenlang auf ihren Füßen warm!"),
  F("🦁", "Ein Löwe schläft fast den ganzen Tag – bis zu zwanzig Stunden!"),
  F("🦁", "Nur Löwen-Männchen haben eine große Mähne!"),
  F("🐬", "Delfine rufen sich gegenseitig mit Namen – mit Pfeiftönen!"),
  F("🐬", "Delfine schlafen mit einem Auge offen!"),
  F("🐌", "Eine Schnecke kann über eine Rasierklinge kriechen, ohne sich zu schneiden!"),
  F("🐌", "Schnecken haben tausende winzige Zähnchen auf ihrer Zunge!"),
  F("🦉", "Eulen können ihren Kopf fast einmal ganz herumdrehen!"),
  F("🦉", "Eulen fliegen fast lautlos – ihre Beute hört sie nicht kommen!"),
  F("🐼", "Pandas essen fast den ganzen Tag Bambus – bis zu vierzehn Stunden!"),
  F("🐼", "Ein neugeborener Panda ist so klein wie eine Maus!"),
  F("🦓", "Jedes Zebra hat ein eigenes Streifenmuster – wie dein Fingerabdruck!"),
  F("🐸", "Frösche schlucken mit ihren Augen – sie drücken das Essen runter!"),
  F("🐸", "Ein Frosch kann viel weiter springen, als er selbst lang ist!"),
  F("🐫", "Kamele speichern Fett im Höcker – nicht Wasser!"),
  F("🐫", "Kamele können ihre Nasenlöcher zumachen, damit kein Sand reinkommt!"),
  F("🦈", "Haie gab es schon, bevor es Bäume gab!"),
  F("🦈", "Haie verlieren ständig Zähne – und es wachsen immer neue nach!"),
  F("🐜", "Eine Ameise kann das Fünfzigfache ihres eigenen Gewichts tragen!"),
  F("🐜", "Ameisen haben keine Ohren – sie spüren Erschütterungen mit den Beinen!"),
  F("🐨", "Koalas schlafen bis zu zwanzig Stunden am Tag!"),
  F("🐨", "Koalas haben Fingerabdrücke, die fast wie unsere aussehen!"),
  F("🦘", "Ein Känguru kann nicht rückwärts hüpfen!"),
  F("🦘", "Känguru-Babys sind bei der Geburt so klein wie ein Gummibärchen!"),
  F("🐢", "Manche Schildkröten werden über hundert Jahre alt!"),
  F("🐢", "Eine Schildkröte kann ihren Panzer nicht ausziehen – er gehört zu ihr!"),
  F("🐇", "Hasen und Kaninchen können fast rundherum sehen, ohne den Kopf zu drehen!"),
  F("🐰", "Die Zähne von Kaninchen wachsen das ganze Leben lang!"),
  F("🐶", "Hunde riechen tausendmal besser als Menschen!"),
  F("🐶", "Jeder Hund hat einen einzigartigen Nasenabdruck!"),
  F("🐱", "Katzen schlafen etwa zwei Drittel ihres Lebens!"),
  F("🐱", "Katzen können im Dunkeln viel besser sehen als wir!"),
  F("🐮", "Kühe haben beste Freundinnen und werden traurig, wenn sie getrennt sind!"),
  F("🐷", "Schweine sind sehr schlau – sie können Puzzle-Spiele lernen!"),
  F("🐷", "Schweine suhlen sich im Schlamm, um sich abzukühlen!"),
  F("🐴", "Pferde können im Stehen schlafen!"),
  F("🐴", "Pferde haben die größten Augen von allen Tieren, die an Land leben!"),
  F("🐑", "Aus der Wolle von einem Schaf kann man mehrere Pullover stricken!"),
  F("🐐", "Ziegen haben rechteckige Pupillen!"),
  F("🐔", "Hühner können sich über hundert Gesichter merken!"),
  F("🐣", "Ein Küken pickt sich mit einem kleinen Eizahn selbst aus dem Ei!"),
  F("🦆", "Enten haben wasserdichte Federn – das Wasser perlt einfach ab!"),
  F("🦢", "Schwäne bleiben ihr ganzes Leben lang mit ihrem Partner zusammen!"),
  F("🦜", "Papageien können Wörter nachsprechen!"),
  F("🐦", "Ein Kolibri kann rückwärts fliegen – als einziger Vogel!"),
  F("🐦", "Der Kolibri ist so klein, dass er in deine Hand passt!"),
  F("🦅", "Ein Adler sieht eine Maus aus über einem Kilometer Entfernung!"),
  F("🦩", "Flamingos sind rosa, weil sie rosa Krebschen fressen!"),
  F("🦩", "Flamingos stehen oft auf einem Bein – auch beim Schlafen!"),
  F("🦇", "Fledermäuse schlafen mit dem Kopf nach unten!"),
  F("🦇", "Fledermäuse finden im Dunkeln den Weg mit ihren Ohren!"),
  F("🐻", "Bären schlafen fast den ganzen Winter durch!"),
  F("🐻‍❄️", "Eisbären haben unter dem weißen Fell schwarze Haut!"),
  F("🐺", "Wölfe heulen, um ihre Familie zu rufen!"),
  F("🦊", "Ein Fuchs hört eine Maus unter dem Schnee!"),
  F("🦔", "Ein Igel hat mehr als fünftausend Stacheln!"),
  F("🦔", "Igel rollen sich bei Gefahr zu einer stacheligen Kugel zusammen!"),
  F("🐭", "Mäuse können durch ein Loch so klein wie eine Münze schlüpfen!"),
  F("🐿️", "Eichhörnchen vergessen viele ihrer versteckten Nüsse – daraus wachsen neue Bäume!"),
  F("🦫", "Biber bauen ganze Dämme aus Ästen – mit ihren Zähnen!"),
  F("🐊", "Krokodile können ihre Zunge nicht herausstrecken!"),
  F("🦎", "Wenn eine Eidechse ihren Schwanz verliert, wächst er wieder nach!"),
  F("🦎", "Geckos können an der Decke laufen!"),
  F("🐍", "Schlangen riechen mit ihrer Zunge!"),
  F("🐍", "Schlangen haben keine Augenlider – sie können nicht blinzeln!"),
  F("🐟", "Fische schlafen mit offenen Augen – sie haben keine Augenlider!"),
  F("🐠", "Der Clownfisch wohnt in einer Anemone, die alle anderen Fische sticht!"),
  F("🐡", "Ein Kugelfisch pumpt sich bei Gefahr zu einer Kugel auf!"),
  F("🦀", "Krabben laufen seitwärts!"),
  F("🦞", "Ein Hummer kann über hundert Jahre alt werden!"),
  F("🦑", "Ein Riesenkalmar hat Augen so groß wie ein Fußball!"),
  F("🐳", "Der Blauwal ist das größte Tier, das je gelebt hat – größer als jeder Dinosaurier!"),
  F("🐳", "Das Herz eines Blauwals ist so groß wie ein kleines Auto!"),
  F("🐋", "Wale sind keine Fische – sie atmen Luft wie du!"),
  F("🦭", "Robben können unter Wasser die Luft länger anhalten als jeder Mensch!"),
  F("🐆", "Der Gepard ist das schnellste Landtier – schneller als ein Auto in der Stadt!"),
  F("🐆", "Ein Gepard kann nicht brüllen – er miaut fast wie eine Katze!"),
  F("🐅", "Tiger haben nicht nur gestreiftes Fell, sondern auch gestreifte Haut!"),
  F("🦏", "Das Horn vom Nashorn besteht aus dem gleichen Stoff wie deine Fingernägel!"),
  F("🦛", "Nilpferde können nicht schwimmen – sie laufen unter Wasser über den Boden!"),
  F("🦛", "Nilpferde haben eine rosa Schutzcreme auf der Haut – die machen sie selbst!"),
  F("🦍", "Gorillas schlagen sich auf die Brust, um zu zeigen, wie stark sie sind!"),
  F("🐵", "Affen gähnen, wenn sie müde sind – genau wie du!"),
  F("🦥", "Faultiere bewegen sich so langsam, dass Moos auf ihrem Fell wächst!"),
  F("🦥", "Ein Faultier braucht einen ganzen Tag, um einen Baum hochzuklettern!"),
  F("🦦", "Otter halten beim Schlafen Händchen, damit sie nicht wegtreiben!"),
  F("🦨", "Ein Stinktier kann mit seinem Gestank Tiere aus weiter Entfernung vertreiben!"),
  F("🦚", "Nur Pfauen-Männchen haben das riesige bunte Federrad!"),
  F("🦃", "Der Truthahn kann seine Kopffarbe ändern, wenn er aufgeregt ist!"),
  F("🐞", "Ein Marienkäfer frisst an einem Tag bis zu fünfzig Blattläuse!"),
  F("🐞", "Die Punkte auf dem Marienkäfer verraten nicht sein Alter!"),
  F("🕷️", "Spinnenfäden sind stärker als ein Stahldraht, der genauso dünn ist!"),
  F("🕷️", "Spinnen sind keine Insekten – sie haben acht Beine, Insekten nur sechs!"),
  F("🦗", "Grillen haben ihre Ohren an den Beinen!"),
  F("🐛", "Ein Regenwurm hat kein Auge – er spürt das Licht mit seiner Haut!"),
  F("🐛", "Regenwürmer lockern die Erde und helfen den Pflanzen beim Wachsen!"),
  F("🦟", "Nur weibliche Mücken stechen!"),
  F("🐝", "Die Königin ist die einzige Biene im Stock, die Eier legt!"),
  F("🦋", "Der größte Schmetterling ist so groß wie ein Teller!"),
  F("🦕", "Manche Dinosaurier waren so lang wie drei Busse hintereinander!"),
  F("🦖", "Der T-Rex hatte Zähne so lang wie eine Banane!"),
  F("🦕", "Aus den Dinosauriern sind die Vögel geworden – Hühner sind ihre Verwandten!"),
  F("🦖", "Einige Dinosaurier waren so klein wie ein Huhn!"),

  // ---------- Dein Körper ----------
  F("🧠", "Dein Gehirn wächst beim Lernen – wie ein Muskel beim Sport!"),
  F("🧠", "Dein Gehirn arbeitet sogar dann, wenn du schläfst!"),
  F("😴", "Beim Schlafen sortiert dein Kopf alles, was du gelernt hast!"),
  F("😴", "Kinder brauchen mehr Schlaf als Erwachsene, weil sie so viel wachsen!"),
  F("❤️", "Dein Herz schlägt an einem Tag über hunderttausend Mal!"),
  F("❤️", "Dein Herz ist ungefähr so groß wie deine Faust!"),
  F("🦴", "Babys haben mehr Knochen als Erwachsene – manche wachsen später zusammen!"),
  F("🦴", "Der kleinste Knochen sitzt in deinem Ohr – er ist so klein wie ein Reiskorn!"),
  F("🦴", "Der längste Knochen ist in deinem Oberschenkel!"),
  F("👅", "Kein Mensch hat den gleichen Zungenabdruck wie du!"),
  F("👅", "Deine Zunge ist der beweglichste Muskel in deinem Körper!"),
  F("🤧", "Ein Nieser ist schneller als ein Auto auf der Autobahn!"),
  F("👃", "Deine Nase kann über tausend verschiedene Gerüche unterscheiden!"),
  F("👀", "Du blinzelst über zehntausend Mal am Tag – ohne es zu merken!"),
  F("👀", "Deine Augen sind schon bei der Geburt fast so groß wie bei Erwachsenen!"),
  F("👂", "Deine Ohren helfen dir, das Gleichgewicht zu halten!"),
  F("🦷", "Milchzähne fallen aus, damit die großen Zähne Platz haben!"),
  F("🦷", "Der Zahnschmelz ist das Härteste an deinem ganzen Körper!"),
  F("👣", "In deinen Füßen sind über fünfzig Knochen!"),
  F("💪", "Zum Lächeln brauchst du viele kleine Muskeln im Gesicht!"),
  F("🩸", "Dein Blut fließt in einer Minute einmal durch den ganzen Körper!"),
  F("🫁", "Du atmest über zwanzigtausend Mal am Tag!"),
  F("💇", "Deine Haare wachsen jeden Monat etwa einen Zentimeter!"),
  F("💅", "Fingernägel wachsen schneller als Fußnägel!"),
  F("🖐️", "Deine Fingerabdrücke hat sonst niemand auf der ganzen Welt!"),
  F("🤗", "Umarmen macht glücklich – dein Körper schüttet dabei Glücksstoffe aus!"),
  F("😂", "Lachen ist gesund – es stärkt sogar dein Herz!"),
  F("🥱", "Gähnen ist ansteckend – schau mal, wer bei dir mitgähnt!"),
  F("🍎", "Ein Apfel am Morgen macht wacher als man denkt!"),
  F("💧", "Dein Körper besteht zu mehr als der Hälfte aus Wasser!"),
  F("🧒", "Du wächst nachts mehr als am Tag!"),

  // ---------- Weltall ----------
  F("⭐", "Es gibt mehr Sterne am Himmel als Sandkörner an allen Stränden!"),
  F("⭐", "Das Licht von manchen Sternen ist älter als deine Oma!"),
  F("🌙", "Der Mond ist so weit weg, dass ein Auto dahin ein halbes Jahr fahren müsste!"),
  F("🌙", "Auf dem Mond gibt es keinen Wind – Fußabdrücke bleiben für immer!"),
  F("🌙", "Der Mond leuchtet nicht selbst – er wird von der Sonne angestrahlt!"),
  F("☀️", "In die Sonne passen mehr als eine Million Erden hinein!"),
  F("☀️", "Das Licht der Sonne braucht acht Minuten bis zu dir!"),
  F("☀️", "Die Sonne ist ein Stern – nur viel näher als die anderen!"),
  F("🌍", "Die Erde dreht sich – deshalb gibt es Tag und Nacht!"),
  F("🌍", "Die Erde ist eine Kugel, keine Scheibe!"),
  F("🌍", "Mehr als die Hälfte der Erde ist von Wasser bedeckt!"),
  F("🪐", "Der Saturn hat Ringe aus Eis und Steinen!"),
  F("🪐", "Der Saturn ist so leicht, dass er auf einem riesigen Meer schwimmen würde!"),
  F("🔴", "Der Mars ist rot, weil sein Staub rostig ist!"),
  F("🪐", "Auf dem Jupiter tobt ein Sturm, der größer ist als die ganze Erde!"),
  F("🚀", "Eine Rakete fliegt schneller als hundert Rennautos zusammen!"),
  F("🚀", "Astronauten schweben im Weltall, weil dort fast nichts nach unten zieht!"),
  F("👩‍🚀", "Astronauten werden im Weltall ein bisschen größer!"),
  F("👩‍🚀", "Im Weltall kann man nicht weinen – die Tränen bleiben am Auge kleben!"),
  F("🛰️", "Die Raumstation fliegt in eineinhalb Stunden einmal um die ganze Erde!"),
  F("☄️", "Sternschnuppen sind kleine Steinchen, die in der Luft verglühen!"),
  F("🌌", "Unsere Galaxie heißt Milchstraße – sie sieht aus wie ein Wirbel!"),
  F("🌑", "Bei einer Sonnenfinsternis schiebt sich der Mond vor die Sonne!"),
  F("🔭", "Mit einem Fernrohr siehst du die Krater auf dem Mond!"),

  // ---------- Natur & Wetter ----------
  F("🌈", "Ein Regenbogen hat immer die gleichen sieben Farben – in der gleichen Reihenfolge!"),
  F("🌈", "Einen Regenbogen siehst du nur, wenn die Sonne hinter dir steht!"),
  F("❄️", "Keine Schneeflocke sieht aus wie eine andere!"),
  F("❄️", "Schnee ist eigentlich durchsichtig – er sieht nur weiß aus!"),
  F("⛈️", "Der Blitz kommt immer vor dem Donner, weil Licht schneller ist als Schall!"),
  F("⚡", "Ein Blitz ist heißer als die Oberfläche der Sonne!"),
  F("☁️", "Wolken sind winzige Wassertröpfchen – und trotzdem tonnenschwer!"),
  F("🌧️", "Regentropfen sind nicht spitz – sie sehen aus wie kleine Brötchen!"),
  F("🌬️", "Wind ist einfach Luft, die sich bewegt!"),
  F("🌊", "Meerwasser ist salzig, weil Flüsse Salz aus den Bergen hineintragen!"),
  F("🌊", "Die tiefste Stelle im Meer ist tiefer, als der höchste Berg hoch ist!"),
  F("🏔️", "Auf sehr hohen Bergen liegt auch im Sommer Schnee!"),
  F("🌋", "In einem Vulkan ist es so heiß, dass Steine flüssig werden!"),
  F("🏝️", "Es gibt Inseln, die aus Vulkanen entstanden sind!"),
  F("💧", "Das Wasser, das du trinkst, gab es schon zur Zeit der Dinosaurier!"),
  F("💧", "Wasser kann drei Dinge sein: Eis, Wasser und Dampf!"),
  F("🌳", "Bäume können sich über ihre Wurzeln Nachrichten schicken!"),
  F("🌳", "Ein Baum wächst jedes Jahr einen neuen Ring – so kann man sein Alter zählen!"),
  F("🌳", "Bäume machen die Luft, die wir zum Atmen brauchen!"),
  F("🌲", "Manche Bäume sind über tausend Jahre alt!"),
  F("🌻", "Sonnenblumen drehen ihre Köpfe den ganzen Tag mit der Sonne mit!"),
  F("🌷", "Tulpen wachsen aus Zwiebeln – aber nicht zum Essen!"),
  F("🌵", "Ein Kaktus speichert Wasser für viele Monate!"),
  F("🍄", "Pilze sind keine Pflanzen und keine Tiere – sie sind etwas ganz Eigenes!"),
  F("🍂", "Blätter werden im Herbst bunt, weil das Grün verschwindet!"),
  F("🌱", "In jedem Samen steckt schon eine ganze Pflanze!"),
  F("🐾", "Im Wald leben in einer Handvoll Erde mehr Lebewesen als Menschen auf der Erde!"),
  F("🏜️", "In der Wüste kann es nachts richtig kalt werden!"),
  F("🧊", "Am Nordpol gibt es Eisbären, am Südpol Pinguine – aber nie beide zusammen!"),
  F("🌅", "Die Sonne geht immer im Osten auf und im Westen unter!"),

  // ---------- Essen ----------
  F("🍯", "Honig wird niemals schlecht – er hält tausende Jahre!"),
  F("🍌", "Bananen wachsen nach oben, nicht nach unten!"),
  F("🍌", "Eine Banane ist eigentlich eine Beere!"),
  F("🥕", "Früher waren Karotten lila statt orange!"),
  F("🥕", "Karotten wachsen unter der Erde – nur das Grün schaut heraus!"),
  F("🍓", "Die Erdbeere trägt ihre kleinen Kerne außen auf der Haut!"),
  F("🍎", "Äpfel schwimmen, weil sie zu einem Viertel aus Luft bestehen!"),
  F("🍎", "Es gibt tausende verschiedene Apfelsorten!"),
  F("🍅", "Die Tomate ist eigentlich eine Frucht, kein Gemüse!"),
  F("🥒", "Eine Gurke besteht fast nur aus Wasser!"),
  F("🍉", "Eine Wassermelone besteht fast ganz aus Wasser – daher der Name!"),
  F("🥔", "Kartoffeln kommen ursprünglich aus Südamerika, von hohen Bergen!"),
  F("🍫", "Schokolade wird aus Kakaobohnen gemacht – die wachsen an Bäumen!"),
  F("🍫", "Früher hat man Kakao getrunken, nicht gegessen!"),
  F("🧀", "Käse wird aus Milch gemacht – manchmal mit Löchern!"),
  F("🥛", "Aus der Milch einer Kuh kann man Butter, Käse und Joghurt machen!"),
  F("🍞", "Brot wird aus Mehl gemacht, und Mehl aus gemahlenen Körnern!"),
  F("🍿", "Popcorn platzt, weil das Wasser im Maiskorn beim Erhitzen explodiert!"),
  F("🍦", "Speiseeis gab es schon vor über tausend Jahren – aus Schnee und Honig!"),
  F("🥜", "Erdnüsse sind gar keine Nüsse – sie wachsen unter der Erde!"),
  F("🌽", "Ein Maiskolben hat meistens eine gerade Anzahl Reihen!"),
  F("🍋", "Zitronen sind so sauer, dass man davon lustige Gesichter macht!"),
  F("🥚", "Ein Ei, das schwimmt, ist alt – ein frisches Ei sinkt!"),
  F("🍝", "Nudeln gibt es in hunderten Formen – Spirale, Schleife, Muschel!"),
  F("🍕", "Die erste Pizza kam aus Italien, aus der Stadt Neapel!"),
  F("🧅", "Zwiebeln bringen dich zum Weinen, weil sie beim Schneiden einen Stoff freisetzen!"),
  F("🫐", "Blaubeeren färben deine Zunge blau!"),
  F("🍇", "Rosinen sind getrocknete Weintrauben!"),

  // ---------- Buchstaben & Zahlen ----------
  F("🔤", "Das Alphabet hat 26 Buchstaben – und du lernst sie alle!"),
  F("🔤", "Das E ist der häufigste Buchstabe in deutschen Wörtern!"),
  F("🔤", "Das Q ist ganz selten – und fast immer kommt danach ein U!"),
  F("🔤", "Die Buchstaben A, E, I, O und U heißen Vokale – die kann man lange singen!"),
  F("🔤", "Das Wort Alphabet kommt von den ersten zwei griechischen Buchstaben: Alpha und Beta!"),
  F("📚", "Das längste deutsche Wort hat über sechzig Buchstaben!"),
  F("📖", "Früher haben Mönche jedes Buch mit der Hand abgeschrieben!"),
  F("✏️", "Ein einziger Bleistift kann eine Linie zeichnen, die viele Kilometer lang ist!"),
  F("🔢", "Die Null wurde erst viel später erfunden als die anderen Zahlen!"),
  F("🔢", "Unsere Zahlen kommen ursprünglich aus Indien!"),
  F("🔢", "Zählen mit den Fingern ist der Grund, warum wir bis zehn zählen und dann neu anfangen!"),
  F("💯", "Hundert ist eine Eins mit zwei Nullen – riesig!"),
  F("🔟", "Zehn Finger, zehn Zehen – deshalb ist die Zehn so wichtig!"),
  F("7️⃣", "Eine Woche hat sieben Tage – und ein Regenbogen sieben Farben!"),
  F("🕐", "Ein Tag hat 24 Stunden, und eine Stunde hat 60 Minuten!"),
  F("📅", "Ein Jahr hat 12 Monate und 365 Tage – manchmal einen mehr!"),
  F("🎲", "Bei einem Würfel ergeben die gegenüberliegenden Seiten immer sieben!"),
  F("🔺", "Ein Dreieck hat drei Ecken, ein Viereck vier – so einfach!"),
  F("⚪", "Ein Kreis hat gar keine Ecken!"),
  F("🐝", "Bienenwaben sind Sechsecke – so passt am meisten Honig hinein!"),

  // ---------- Alltag, Technik & Menschen ----------
  F("🚗", "Die ersten Autos waren langsamer als ein Fahrrad!"),
  F("🚂", "Die schnellsten Züge fahren so schnell wie ein Flugzeug beim Start!"),
  F("✈️", "Flugzeuge fliegen so hoch, dass es draußen eiskalt ist!"),
  F("🚲", "Ein Fahrrad kippt nicht um, solange du fährst – wegen der drehenden Räder!"),
  F("🚢", "Riesige Schiffe aus Eisen schwimmen, weil sie innen viel Luft haben!"),
  F("🎈", "Heißluftballons steigen, weil warme Luft nach oben will!"),
  F("💡", "Die Glühbirne wurde vor ungefähr 150 Jahren erfunden!"),
  F("📱", "Die ersten Handys waren so groß und schwer wie ein Ziegelstein!"),
  F("💻", "Der erste Computer war so groß wie ein ganzes Zimmer!"),
  F("🤖", "Das Wort Roboter kommt aus Tschechien und bedeutet Arbeit!"),
  F("🎵", "Musik kann dich froh oder ruhig machen – dein Gehirn liebt Musik!"),
  F("🎸", "Eine Gitarre hat sechs Saiten – jede klingt anders!"),
  F("🥁", "Die Trommel ist eines der ältesten Instrumente der Welt!"),
  F("🎨", "Aus Rot, Gelb und Blau kann man fast alle anderen Farben mischen!"),
  F("🎨", "Rot und Gelb zusammen ergeben Orange!"),
  F("🧸", "Der Teddybär ist nach einem Präsidenten benannt, der Teddy hieß!"),
  F("🧱", "Lego-Steine von heute passen noch auf Steine von vor sechzig Jahren!"),
  F("⚽", "Beim Fußball spielen elf Spieler pro Mannschaft!"),
  F("🏊", "Im Salzwasser schwimmst du leichter als im Schwimmbad!"),
  F("🏰", "Ritter brauchten Hilfe, um ihre schwere Rüstung anzuziehen!"),
  F("🛝", "Das Wort Kindergarten benutzen sogar Menschen in Amerika!"),
  F("🏠", "Die Deutschen sagen Schule – die Griechen hatten dafür ein Wort, das Freizeit bedeutete!"),
  F("🌉", "Die längste Brücke der Welt ist über hundert Kilometer lang!"),
  F("🗼", "Der Eiffelturm wird im Sommer ein Stückchen höher, weil sich das Eisen ausdehnt!"),
  F("🏛️", "Die Pyramiden in Ägypten sind über viertausend Jahre alt!"),
  F("🧭", "Ein Kompass zeigt immer nach Norden!"),
  F("🔑", "Schlüssel gibt es schon seit über dreitausend Jahren!"),
  F("🕯️", "Vor dem elektrischen Licht las man abends bei Kerzenschein!"),
  F("🧼", "Seife macht Bakterien den Garaus – Händewaschen hilft wirklich!"),
  F("🪥", "Zähneputzen sollte so lange dauern wie ein kurzes Lied!"),
  F("🌡️", "Deine Körpertemperatur ist fast immer gleich – ungefähr 37 Grad!"),
  F("🎂", "Kerzen auf dem Geburtstagskuchen gibt es schon seit über zweihundert Jahren!"),
  F("🐾", "Der Hund war das erste Tier, das mit Menschen zusammenlebte!"),
  F("👶", "Babys können schon vor der Geburt Stimmen hören!"),
  F("👵", "Deine Oma und dein Opa waren auch mal so klein wie du!"),
  F("🌍", "Auf der Welt werden über siebentausend verschiedene Sprachen gesprochen!"),
  F("🇩🇪", "In Deutschland leben über achtzig Millionen Menschen!"),
  F("🍞", "In Deutschland gibt es über dreitausend verschiedene Brotsorten!"),
  F("🚂", "Die erste Eisenbahn in Deutschland fuhr von Nürnberg nach Fürth!"),
  F("🏁", "Der Buchstabe Z ist der letzte im Alphabet – du hast es fast geschafft!"),
];

// ---------- Auswahl ohne Wiederholung – auch über mehrere Lektionen ----------

const SEEN_KEY = "anton-lernapp-facts-seen-v1";

function loadSeen() {
  if (typeof window === "undefined") return [];
  try {
    const arr = JSON.parse(window.localStorage.getItem(SEEN_KEY) || "[]");
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

function saveSeen(arr) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(SEEN_KEY, JSON.stringify(arr));
  } catch {}
}

// Liefert einen noch nicht gezeigten Fakt. Erst wenn alle einmal dran
// waren, beginnt die Runde von vorn.
export function pickFact() {
  let seen = loadSeen();
  let unseen = FUN_FACTS.map((_, i) => i).filter((i) => !seen.includes(i));
  if (!unseen.length) {
    seen = [];
    unseen = FUN_FACTS.map((_, i) => i);
  }
  const idx = unseen[Math.floor(Math.random() * unseen.length)];
  saveSeen([...seen, idx]);
  return FUN_FACTS[idx];
}
